const CONTRACT_STATUSES = {
  DRAFT: 'draft',
  RESERVED: 'reserved',
  SIGNED: 'signed',
  EFFECTIVE: 'effective',
  VOIDED: 'voided'
};

const STATUS_NAMES = {
  draft: '草稿',
  reserved: '预留中',
  signed: '已签约',
  effective: '已生效',
  voided: '已作废'
};

const PLOT_STATUSES = {
  AVAILABLE: '空闲',
  RESERVED: '预留中',
  OCCUPIED: '已占用',
  MAINTENANCE: '维修中'
};

const ALLOWED_STATUS_TRANSITIONS = {
  [CONTRACT_STATUSES.DRAFT]: [CONTRACT_STATUSES.RESERVED, CONTRACT_STATUSES.SIGNED, CONTRACT_STATUSES.VOIDED],
  [CONTRACT_STATUSES.RESERVED]: [CONTRACT_STATUSES.DRAFT, CONTRACT_STATUSES.SIGNED, CONTRACT_STATUSES.VOIDED],
  [CONTRACT_STATUSES.SIGNED]: [CONTRACT_STATUSES.EFFECTIVE, CONTRACT_STATUSES.VOIDED],
  [CONTRACT_STATUSES.EFFECTIVE]: [CONTRACT_STATUSES.VOIDED],
  [CONTRACT_STATUSES.VOIDED]: []
};

const VALID_STATUSES_FOR_UPDATE = [
  CONTRACT_STATUSES.DRAFT,
  CONTRACT_STATUSES.RESERVED,
  CONTRACT_STATUSES.SIGNED
];

const VALID_STATUSES_FOR_SIGN = [
  CONTRACT_STATUSES.DRAFT,
  CONTRACT_STATUSES.RESERVED
];

const VALID_STATUSES_FOR_PAY = [
  CONTRACT_STATUSES.RESERVED,
  CONTRACT_STATUSES.SIGNED,
  CONTRACT_STATUSES.EFFECTIVE
];

const VALID_STATUSES_FOR_DELETE = [
  CONTRACT_STATUSES.DRAFT
];

const VALID_STATUSES_FOR_RENEW = [
  CONTRACT_STATUSES.RESERVED
];

module.exports = {
  CONTRACT_STATUSES,
  STATUS_NAMES,
  PLOT_STATUSES,
  ALLOWED_STATUS_TRANSITIONS,
  VALID_STATUSES_FOR_UPDATE,
  VALID_STATUSES_FOR_SIGN,
  VALID_STATUSES_FOR_PAY,
  VALID_STATUSES_FOR_DELETE,
  VALID_STATUSES_FOR_RENEW
};
